import json
import os
from typing import Any, Dict, List

from groq import Groq

from core.models.phase2models.RequirementsArtifact import RequirementsArtifact
from core.models.phase3models.PlanArtifact import PlanStep
from core.models.phase4models.CodeChangeArtifact import StepExecutionResult, FileChange
from core.gates.phase4gates.gatePhase4 import CodeIntegrityGate
from core.utils import make_json_safe


class CodeSynthesizer:
    def __init__(self, model: str = "llama-3.3-70b-versatile"):
        api_key = os.getenv("GROQ_API")
        if not api_key:
            raise RuntimeError("⚠️ [CodeSynthesizer] GROQ_API not found in environment")

        self.client = Groq(api_key=api_key)
        self.model = model

    async def generate_step_code(self, step: PlanStep, requirements: RequirementsArtifact) -> StepExecutionResult:
        """
        Generates code for a single plan step.
        """
        prompt = self._build_prompt(step, requirements)
        raw_json = self._call_groq(prompt)
        
        # ✅ Gate validates the RAW LLM OUTPUT STRING
        is_valid, msg = CodeIntegrityGate.validate(raw_json)
        if not is_valid:
            # Instead of crashing, we can return a failed step result with the error
            return StepExecutionResult(
                step_id=step.step_id,
                status="failed",
                logs=f"Gate validation failed: {msg}\nRaw Output: {raw_json[:200]}..."
            )

        data = self._safe_json_loads(raw_json)
        
        # Convert LLM output to StepExecutionResult
        changes_data = data.get("changes", [])
        changes = [FileChange(**c) for c in changes_data]
        
        return StepExecutionResult(
            step_id=step.step_id,
            status="success",
            changes=changes,
            logs=data.get("reasoning", "Generated by LLM")
        )

    def _build_prompt(self, step: PlanStep, requirements: RequirementsArtifact) -> str:
        req_context = make_json_safe(requirements.model_dump())
        step_context = make_json_safe(step.model_dump())

        return f"""
You are the Senior Developer for the Interlock System (Phase 4).

GOAL:
Implement the code for the following Plan Step based on the Requirements.
You must return the FULL content of the file(s) to be created or modified.

CONTEXT:
Requirements: {json.dumps(req_context, ensure_ascii=False)}

CURRENT STEP TO IMPLEMENT:
{json.dumps(step_context, ensure_ascii=False)}

INSTRUCTIONS:
1. Analyze the step description and the linked requirement.
2. Write production-quality Python code (Pydantic models, Async functions, etc.).
3. If the step asks to create a file, provide the full content.
4. If the step asks to modify, provide the full new content (for now).
5. Output MUST be valid JSON matching the schema below.

OUTPUT JSON STRUCTURE:
{{
  "reasoning": "Brief explanation of the implementation...",
  "changes": [
    {{
      "file_path": "core/models/NewModel.py",
      "action": "create",  // or "modify"
      "description": "Created the data model for X",
      "content": "from pydantic import BaseModel\\n\\nclass X(BaseModel):\\n    ..."
    }}
  ]
}}
""".strip()

    def _call_groq(self, prompt: str) -> str:
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": "You output ONLY JSON that matches the provided schema."},
                    {"role": "user", "content": prompt},
                ],
                response_format={"type": "json_object"},
                temperature=0.2,
            )
            return response.choices[0].message.content or "{}"
        except Exception as e:
            raise RuntimeError(f"❌ [CodeSynthesizer] Groq call failed: {e}") from e

    def _safe_json_loads(self, raw: str) -> Dict[str, Any]:
        raw = (raw or "").strip()
        if not raw:
            return {}

        try:
            data = json.loads(raw)
            if not isinstance(data, dict):
                raise ValueError("Root JSON must be an object/dict.")
            return data
        except Exception as e:
            raise ValueError(
                f"❌ [CodeSynthesizer] Invalid JSON returned by LLM: {e}\nRAW:\n{raw}"
            ) from e
